spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: nebula-server-websocket
  cloud:
    consul:
      discovery:
        tags: ver=1.0, provider=nebula
server:
  port: 9001

nebula:
  websocket:
    hostname: 0.0.0.0
    port: 3001
    namespaces:
      lyra:
        name: lyra
        authorized-cookie: SESSIONUID
      galaxy:
        name: galaxy
        authorized-cookie: JSESSIONID
      channel:
        name: channel
        authorized-cookie: JSESSIONID
